[tool.poetry]
name = "mine-sim"
version = "0.1.0"
description = ""
authors = ["konrad-h <konradhartmannv@hotmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
Flask = "^2.0.1"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.7b0"
